/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as CadastroClienteRouteImport } from './routes/cadastro-cliente'
import { Route as CategoriasRouteImport } from './routes/categorias'
import { Route as ClienteLoginRouteImport } from './routes/cliente-login'
import { Route as ClientesRouteRouteImport } from './routes/clientes/route'
import { Route as DefinirSenhaRouteImport } from './routes/definir-senha'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as EntrarAdminRouteImport } from './routes/entrar-admin'
import { Route as EventosRouteImport } from './routes/eventos'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as PreservacaoRouteImport } from './routes/preservacao'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminClientsRouteRouteImport } from './routes/admin/clients/route'
import { Route as AdminEventsRouteImport } from './routes/admin/events'
import { Route as AdminPromosRouteImport } from './routes/admin/promos'
import { Route as CategoriaSlugRouteImport } from './routes/categoria.$slug'
import { Route as ClientesIndexRouteImport } from './routes/clientes/index'
import { Route as ClientesAvaliacoesRouteImport } from './routes/clientes/avaliacoes'
import { Route as ClientesContatosRouteImport } from './routes/clientes/contatos'
import { Route as ClientesFavoritosRouteImport } from './routes/clientes/favoritos'
import { Route as ClientesPainelClienteRouteImport } from './routes/clientes/painel-cliente'
import { Route as ClientesPerfilRouteImport } from './routes/clientes/perfil'
import { Route as ClientesVouchersRouteImport } from './routes/clientes/vouchers'
import { Route as PainelIndexRouteImport } from './routes/painel/index'
import { Route as PainelAvaliacoesRouteImport } from './routes/painel/avaliacoes'
import { Route as PainelConfiguracoesRouteImport } from './routes/painel/configuracoes'
import { Route as PainelEstatisticasRouteImport } from './routes/painel/estatisticas'
import { Route as PainelImagensRouteImport } from './routes/painel/imagens'
import { Route as PainelPerfilRouteImport } from './routes/painel/perfil'
import { Route as PainelPromocoesRouteImport } from './routes/painel/promocoes'
import { Route as PainelReservasRouteImport } from './routes/painel/reservas'
import { Route as ParceiroSlugRouteImport } from './routes/parceiro.$slug'
import { Route as AdminClientsIndexRouteImport } from './routes/admin/clients/index'
import { Route as AdminClientsIdRouteImport } from './routes/admin/clients/$id'
import { Route as AdminClientsCreateRouteImport } from './routes/admin/clients/create'
import { Route as AdminPartnersIndexRouteImport } from './routes/admin/partners/index'
import { Route as AdminPartnersCreateRouteImport } from './routes/admin/partners/create'
import { Route as AdminClientsIdEditRouteImport } from './routes/admin/clients/$id.edit'
import { Route as AdminPartnersIdEditRouteImport } from './routes/admin/partners/$id/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroClienteRoute = CadastroClienteRouteImport.update({
  id: '/cadastro-cliente',
  path: '/cadastro-cliente',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasRoute = CategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteLoginRoute = ClienteLoginRouteImport.update({
  id: '/cliente-login',
  path: '/cliente-login',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRouteRoute = ClientesRouteRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const DefinirSenhaRoute = DefinirSenhaRouteImport.update({
  id: '/definir-senha',
  path: '/definir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarAdminRoute = EntrarAdminRouteImport.update({
  id: '/entrar-admin',
  path: '/entrar-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosRoute = EventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const PreservacaoRoute = PreservacaoRouteImport.update({
  id: '/preservacao',
  path: '/preservacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminClientsRouteRoute = AdminClientsRouteRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPromosRoute = AdminPromosRouteImport.update({
  id: '/promos',
  path: '/promos',
  getParentRoute: () => AdminRouteRoute,
} as any)
const CategoriaSlugRoute = CategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIndexRoute = ClientesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientesRouteRoute,
} as any)
const ClientesAvaliacoesRoute = ClientesAvaliacoesRouteImport.update({
  id: '/avaliacoes',
  path: '/avaliacoes',
  getParentRoute: () => ClientesRouteRoute,
} as any)
const ClientesContatosRoute = ClientesContatosRouteImport.update({
  id: '/contatos',
  path: '/contatos',
  getParentRoute: () => ClientesRouteRoute,
} as any)
const ClientesFavoritosRoute = ClientesFavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => ClientesRouteRoute,
} as any)
const ClientesPainelClienteRoute = ClientesPainelClienteRouteImport.update({
  id: '/painel-cliente',
  path: '/painel-cliente',
  getParentRoute: () => ClientesRouteRoute,
} as any)
const ClientesPerfilRoute = ClientesPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => ClientesRouteRoute,
} as any)
const ClientesVouchersRoute = ClientesVouchersRouteImport.update({
  id: '/vouchers',
  path: '/vouchers',
  getParentRoute: () => ClientesRouteRoute,
} as any)
const PainelIndexRoute = PainelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PainelRoute,
} as any)
const PainelAvaliacoesRoute = PainelAvaliacoesRouteImport.update({
  id: '/avaliacoes',
  path: '/avaliacoes',
  getParentRoute: () => PainelRoute,
} as any)
const PainelConfiguracoesRoute = PainelConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => PainelRoute,
} as any)
const PainelEstatisticasRoute = PainelEstatisticasRouteImport.update({
  id: '/estatisticas',
  path: '/estatisticas',
  getParentRoute: () => PainelRoute,
} as any)
const PainelImagensRoute = PainelImagensRouteImport.update({
  id: '/imagens',
  path: '/imagens',
  getParentRoute: () => PainelRoute,
} as any)
const PainelPerfilRoute = PainelPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => PainelRoute,
} as any)
const PainelPromocoesRoute = PainelPromocoesRouteImport.update({
  id: '/promocoes',
  path: '/promocoes',
  getParentRoute: () => PainelRoute,
} as any)
const PainelReservasRoute = PainelReservasRouteImport.update({
  id: '/reservas',
  path: '/reservas',
  getParentRoute: () => PainelRoute,
} as any)
const ParceiroSlugRoute = ParceiroSlugRouteImport.update({
  id: '/parceiro/$slug',
  path: '/parceiro/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClientsIndexRoute = AdminClientsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminClientsRouteRoute,
} as any)
const AdminClientsIdRoute = AdminClientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminClientsRouteRoute,
} as any)
const AdminClientsCreateRoute = AdminClientsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AdminClientsRouteRoute,
} as any)
const AdminPartnersIndexRoute = AdminPartnersIndexRouteImport.update({
  id: '/partners/',
  path: '/partners/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPartnersCreateRoute = AdminPartnersCreateRouteImport.update({
  id: '/partners/create',
  path: '/partners/create',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminClientsIdEditRoute = AdminClientsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AdminClientsIdRoute,
} as any)
const AdminPartnersIdEditRoute = AdminPartnersIdEditRouteImport.update({
  id: '/partners/$id/edit',
  path: '/partners/$id/edit',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/clientes': typeof ClientesRouteRouteWithChildren
  '/buscar': typeof BuscarRoute
  '/cadastro-cliente': typeof CadastroClienteRoute
  '/categorias': typeof CategoriasRoute
  '/cliente-login': typeof ClienteLoginRoute
  '/definir-senha': typeof DefinirSenhaRoute
  '/entrar': typeof EntrarRoute
  '/entrar-admin': typeof EntrarAdminRoute
  '/eventos': typeof EventosRoute
  '/painel': typeof PainelRouteWithChildren
  '/planos': typeof PlanosRoute
  '/preservacao': typeof PreservacaoRoute
  '/admin/clients': typeof AdminClientsRouteRouteWithChildren
  '/admin/events': typeof AdminEventsRoute
  '/admin/promos': typeof AdminPromosRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/clientes/avaliacoes': typeof ClientesAvaliacoesRoute
  '/clientes/contatos': typeof ClientesContatosRoute
  '/clientes/favoritos': typeof ClientesFavoritosRoute
  '/clientes/painel-cliente': typeof ClientesPainelClienteRoute
  '/clientes/perfil': typeof ClientesPerfilRoute
  '/clientes/vouchers': typeof ClientesVouchersRoute
  '/painel/avaliacoes': typeof PainelAvaliacoesRoute
  '/painel/configuracoes': typeof PainelConfiguracoesRoute
  '/painel/estatisticas': typeof PainelEstatisticasRoute
  '/painel/imagens': typeof PainelImagensRoute
  '/painel/perfil': typeof PainelPerfilRoute
  '/painel/promocoes': typeof PainelPromocoesRoute
  '/painel/reservas': typeof PainelReservasRoute
  '/parceiro/$slug': typeof ParceiroSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/clientes/': typeof ClientesIndexRoute
  '/painel/': typeof PainelIndexRoute
  '/admin/clients/$id': typeof AdminClientsIdRouteWithChildren
  '/admin/clients/create': typeof AdminClientsCreateRoute
  '/admin/partners/create': typeof AdminPartnersCreateRoute
  '/admin/clients/': typeof AdminClientsIndexRoute
  '/admin/partners/': typeof AdminPartnersIndexRoute
  '/admin/clients/$id/edit': typeof AdminClientsIdEditRoute
  '/admin/partners/$id/edit': typeof AdminPartnersIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/buscar': typeof BuscarRoute
  '/cadastro-cliente': typeof CadastroClienteRoute
  '/categorias': typeof CategoriasRoute
  '/cliente-login': typeof ClienteLoginRoute
  '/definir-senha': typeof DefinirSenhaRoute
  '/entrar': typeof EntrarRoute
  '/entrar-admin': typeof EntrarAdminRoute
  '/eventos': typeof EventosRoute
  '/planos': typeof PlanosRoute
  '/preservacao': typeof PreservacaoRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/promos': typeof AdminPromosRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/clientes/avaliacoes': typeof ClientesAvaliacoesRoute
  '/clientes/contatos': typeof ClientesContatosRoute
  '/clientes/favoritos': typeof ClientesFavoritosRoute
  '/clientes/painel-cliente': typeof ClientesPainelClienteRoute
  '/clientes/perfil': typeof ClientesPerfilRoute
  '/clientes/vouchers': typeof ClientesVouchersRoute
  '/painel/avaliacoes': typeof PainelAvaliacoesRoute
  '/painel/configuracoes': typeof PainelConfiguracoesRoute
  '/painel/estatisticas': typeof PainelEstatisticasRoute
  '/painel/imagens': typeof PainelImagensRoute
  '/painel/perfil': typeof PainelPerfilRoute
  '/painel/promocoes': typeof PainelPromocoesRoute
  '/painel/reservas': typeof PainelReservasRoute
  '/parceiro/$slug': typeof ParceiroSlugRoute
  '/admin': typeof AdminIndexRoute
  '/clientes': typeof ClientesIndexRoute
  '/painel': typeof PainelIndexRoute
  '/admin/clients/$id': typeof AdminClientsIdRouteWithChildren
  '/admin/clients/create': typeof AdminClientsCreateRoute
  '/admin/partners/create': typeof AdminPartnersCreateRoute
  '/admin/clients': typeof AdminClientsIndexRoute
  '/admin/partners': typeof AdminPartnersIndexRoute
  '/admin/clients/$id/edit': typeof AdminClientsIdEditRoute
  '/admin/partners/$id/edit': typeof AdminPartnersIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/clientes': typeof ClientesRouteRouteWithChildren
  '/buscar': typeof BuscarRoute
  '/cadastro-cliente': typeof CadastroClienteRoute
  '/categorias': typeof CategoriasRoute
  '/cliente-login': typeof ClienteLoginRoute
  '/definir-senha': typeof DefinirSenhaRoute
  '/entrar': typeof EntrarRoute
  '/entrar-admin': typeof EntrarAdminRoute
  '/eventos': typeof EventosRoute
  '/painel': typeof PainelRouteWithChildren
  '/planos': typeof PlanosRoute
  '/preservacao': typeof PreservacaoRoute
  '/admin/clients': typeof AdminClientsRouteRouteWithChildren
  '/admin/events': typeof AdminEventsRoute
  '/admin/promos': typeof AdminPromosRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/clientes/avaliacoes': typeof ClientesAvaliacoesRoute
  '/clientes/contatos': typeof ClientesContatosRoute
  '/clientes/favoritos': typeof ClientesFavoritosRoute
  '/clientes/painel-cliente': typeof ClientesPainelClienteRoute
  '/clientes/perfil': typeof ClientesPerfilRoute
  '/clientes/vouchers': typeof ClientesVouchersRoute
  '/painel/avaliacoes': typeof PainelAvaliacoesRoute
  '/painel/configuracoes': typeof PainelConfiguracoesRoute
  '/painel/estatisticas': typeof PainelEstatisticasRoute
  '/painel/imagens': typeof PainelImagensRoute
  '/painel/perfil': typeof PainelPerfilRoute
  '/painel/promocoes': typeof PainelPromocoesRoute
  '/painel/reservas': typeof PainelReservasRoute
  '/parceiro/$slug': typeof ParceiroSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/clientes/': typeof ClientesIndexRoute
  '/painel/': typeof PainelIndexRoute
  '/admin/clients/$id': typeof AdminClientsIdRouteWithChildren
  '/admin/clients/create': typeof AdminClientsCreateRoute
  '/admin/partners/create': typeof AdminPartnersCreateRoute
  '/admin/clients/': typeof AdminClientsIndexRoute
  '/admin/partners/': typeof AdminPartnersIndexRoute
  '/admin/clients/$id/edit': typeof AdminClientsIdEditRoute
  '/admin/partners/$id/edit': typeof AdminPartnersIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/clientes'
    | '/buscar'
    | '/cadastro-cliente'
    | '/categorias'
    | '/cliente-login'
    | '/definir-senha'
    | '/entrar'
    | '/entrar-admin'
    | '/eventos'
    | '/painel'
    | '/planos'
    | '/preservacao'
    | '/admin/clients'
    | '/admin/events'
    | '/admin/promos'
    | '/categoria/$slug'
    | '/clientes/avaliacoes'
    | '/clientes/contatos'
    | '/clientes/favoritos'
    | '/clientes/painel-cliente'
    | '/clientes/perfil'
    | '/clientes/vouchers'
    | '/painel/avaliacoes'
    | '/painel/configuracoes'
    | '/painel/estatisticas'
    | '/painel/imagens'
    | '/painel/perfil'
    | '/painel/promocoes'
    | '/painel/reservas'
    | '/parceiro/$slug'
    | '/admin/'
    | '/clientes/'
    | '/painel/'
    | '/admin/clients/$id'
    | '/admin/clients/create'
    | '/admin/partners/create'
    | '/admin/clients/'
    | '/admin/partners/'
    | '/admin/clients/$id/edit'
    | '/admin/partners/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/buscar'
    | '/cadastro-cliente'
    | '/categorias'
    | '/cliente-login'
    | '/definir-senha'
    | '/entrar'
    | '/entrar-admin'
    | '/eventos'
    | '/planos'
    | '/preservacao'
    | '/admin/events'
    | '/admin/promos'
    | '/categoria/$slug'
    | '/clientes/avaliacoes'
    | '/clientes/contatos'
    | '/clientes/favoritos'
    | '/clientes/painel-cliente'
    | '/clientes/perfil'
    | '/clientes/vouchers'
    | '/painel/avaliacoes'
    | '/painel/configuracoes'
    | '/painel/estatisticas'
    | '/painel/imagens'
    | '/painel/perfil'
    | '/painel/promocoes'
    | '/painel/reservas'
    | '/parceiro/$slug'
    | '/admin'
    | '/clientes'
    | '/painel'
    | '/admin/clients/$id'
    | '/admin/clients/create'
    | '/admin/partners/create'
    | '/admin/clients'
    | '/admin/partners'
    | '/admin/clients/$id/edit'
    | '/admin/partners/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/clientes'
    | '/buscar'
    | '/cadastro-cliente'
    | '/categorias'
    | '/cliente-login'
    | '/definir-senha'
    | '/entrar'
    | '/entrar-admin'
    | '/eventos'
    | '/painel'
    | '/planos'
    | '/preservacao'
    | '/admin/clients'
    | '/admin/events'
    | '/admin/promos'
    | '/categoria/$slug'
    | '/clientes/avaliacoes'
    | '/clientes/contatos'
    | '/clientes/favoritos'
    | '/clientes/painel-cliente'
    | '/clientes/perfil'
    | '/clientes/vouchers'
    | '/painel/avaliacoes'
    | '/painel/configuracoes'
    | '/painel/estatisticas'
    | '/painel/imagens'
    | '/painel/perfil'
    | '/painel/promocoes'
    | '/painel/reservas'
    | '/parceiro/$slug'
    | '/admin/'
    | '/clientes/'
    | '/painel/'
    | '/admin/clients/$id'
    | '/admin/clients/create'
    | '/admin/partners/create'
    | '/admin/clients/'
    | '/admin/partners/'
    | '/admin/clients/$id/edit'
    | '/admin/partners/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  ClientesRouteRoute: typeof ClientesRouteRouteWithChildren
  BuscarRoute: typeof BuscarRoute
  CadastroClienteRoute: typeof CadastroClienteRoute
  CategoriasRoute: typeof CategoriasRoute
  ClienteLoginRoute: typeof ClienteLoginRoute
  DefinirSenhaRoute: typeof DefinirSenhaRoute
  EntrarRoute: typeof EntrarRoute
  EntrarAdminRoute: typeof EntrarAdminRoute
  EventosRoute: typeof EventosRoute
  PainelRoute: typeof PainelRouteWithChildren
  PlanosRoute: typeof PlanosRoute
  PreservacaoRoute: typeof PreservacaoRoute
  CategoriaSlugRoute: typeof CategoriaSlugRoute
  ParceiroSlugRoute: typeof ParceiroSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro-cliente': {
      id: '/cadastro-cliente'
      path: '/cadastro-cliente'
      fullPath: '/cadastro-cliente'
      preLoaderRoute: typeof CadastroClienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias': {
      id: '/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof CategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente-login': {
      id: '/cliente-login'
      path: '/cliente-login'
      fullPath: '/cliente-login'
      preLoaderRoute: typeof ClienteLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/definir-senha': {
      id: '/definir-senha'
      path: '/definir-senha'
      fullPath: '/definir-senha'
      preLoaderRoute: typeof DefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar-admin': {
      id: '/entrar-admin'
      path: '/entrar-admin'
      fullPath: '/entrar-admin'
      preLoaderRoute: typeof EntrarAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos': {
      id: '/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof EventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preservacao': {
      id: '/preservacao'
      path: '/preservacao'
      fullPath: '/preservacao'
      preLoaderRoute: typeof PreservacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/clients': {
      id: '/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminClientsRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/promos': {
      id: '/admin/promos'
      path: '/promos'
      fullPath: '/admin/promos'
      preLoaderRoute: typeof AdminPromosRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/categoria/$slug': {
      id: '/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/categoria/$slug'
      preLoaderRoute: typeof CategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/': {
      id: '/clientes/'
      path: '/'
      fullPath: '/clientes/'
      preLoaderRoute: typeof ClientesIndexRouteImport
      parentRoute: typeof ClientesRouteRoute
    }
    '/clientes/avaliacoes': {
      id: '/clientes/avaliacoes'
      path: '/avaliacoes'
      fullPath: '/clientes/avaliacoes'
      preLoaderRoute: typeof ClientesAvaliacoesRouteImport
      parentRoute: typeof ClientesRouteRoute
    }
    '/clientes/contatos': {
      id: '/clientes/contatos'
      path: '/contatos'
      fullPath: '/clientes/contatos'
      preLoaderRoute: typeof ClientesContatosRouteImport
      parentRoute: typeof ClientesRouteRoute
    }
    '/clientes/favoritos': {
      id: '/clientes/favoritos'
      path: '/favoritos'
      fullPath: '/clientes/favoritos'
      preLoaderRoute: typeof ClientesFavoritosRouteImport
      parentRoute: typeof ClientesRouteRoute
    }
    '/clientes/painel-cliente': {
      id: '/clientes/painel-cliente'
      path: '/painel-cliente'
      fullPath: '/clientes/painel-cliente'
      preLoaderRoute: typeof ClientesPainelClienteRouteImport
      parentRoute: typeof ClientesRouteRoute
    }
    '/clientes/perfil': {
      id: '/clientes/perfil'
      path: '/perfil'
      fullPath: '/clientes/perfil'
      preLoaderRoute: typeof ClientesPerfilRouteImport
      parentRoute: typeof ClientesRouteRoute
    }
    '/clientes/vouchers': {
      id: '/clientes/vouchers'
      path: '/vouchers'
      fullPath: '/clientes/vouchers'
      preLoaderRoute: typeof ClientesVouchersRouteImport
      parentRoute: typeof ClientesRouteRoute
    }
    '/painel/': {
      id: '/painel/'
      path: '/'
      fullPath: '/painel/'
      preLoaderRoute: typeof PainelIndexRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/avaliacoes': {
      id: '/painel/avaliacoes'
      path: '/avaliacoes'
      fullPath: '/painel/avaliacoes'
      preLoaderRoute: typeof PainelAvaliacoesRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/configuracoes': {
      id: '/painel/configuracoes'
      path: '/configuracoes'
      fullPath: '/painel/configuracoes'
      preLoaderRoute: typeof PainelConfiguracoesRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/estatisticas': {
      id: '/painel/estatisticas'
      path: '/estatisticas'
      fullPath: '/painel/estatisticas'
      preLoaderRoute: typeof PainelEstatisticasRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/imagens': {
      id: '/painel/imagens'
      path: '/imagens'
      fullPath: '/painel/imagens'
      preLoaderRoute: typeof PainelImagensRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/perfil': {
      id: '/painel/perfil'
      path: '/perfil'
      fullPath: '/painel/perfil'
      preLoaderRoute: typeof PainelPerfilRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/promocoes': {
      id: '/painel/promocoes'
      path: '/promocoes'
      fullPath: '/painel/promocoes'
      preLoaderRoute: typeof PainelPromocoesRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/reservas': {
      id: '/painel/reservas'
      path: '/reservas'
      fullPath: '/painel/reservas'
      preLoaderRoute: typeof PainelReservasRouteImport
      parentRoute: typeof PainelRoute
    }
    '/parceiro/$slug': {
      id: '/parceiro/$slug'
      path: '/parceiro/$slug'
      fullPath: '/parceiro/$slug'
      preLoaderRoute: typeof ParceiroSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/clients/': {
      id: '/admin/clients/'
      path: '/'
      fullPath: '/admin/clients/'
      preLoaderRoute: typeof AdminClientsIndexRouteImport
      parentRoute: typeof AdminClientsRouteRoute
    }
    '/admin/clients/$id': {
      id: '/admin/clients/$id'
      path: '/$id'
      fullPath: '/admin/clients/$id'
      preLoaderRoute: typeof AdminClientsIdRouteImport
      parentRoute: typeof AdminClientsRouteRoute
    }
    '/admin/clients/create': {
      id: '/admin/clients/create'
      path: '/create'
      fullPath: '/admin/clients/create'
      preLoaderRoute: typeof AdminClientsCreateRouteImport
      parentRoute: typeof AdminClientsRouteRoute
    }
    '/admin/partners/': {
      id: '/admin/partners/'
      path: '/partners'
      fullPath: '/admin/partners/'
      preLoaderRoute: typeof AdminPartnersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/partners/create': {
      id: '/admin/partners/create'
      path: '/partners/create'
      fullPath: '/admin/partners/create'
      preLoaderRoute: typeof AdminPartnersCreateRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/clients/$id/edit': {
      id: '/admin/clients/$id/edit'
      path: '/edit'
      fullPath: '/admin/clients/$id/edit'
      preLoaderRoute: typeof AdminClientsIdEditRouteImport
      parentRoute: typeof AdminClientsIdRoute
    }
    '/admin/partners/$id/edit': {
      id: '/admin/partners/$id/edit'
      path: '/partners/$id/edit'
      fullPath: '/admin/partners/$id/edit'
      preLoaderRoute: typeof AdminPartnersIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminClientsIdRouteChildren {
  AdminClientsIdEditRoute: typeof AdminClientsIdEditRoute
}

const AdminClientsIdRouteChildren: AdminClientsIdRouteChildren = {
  AdminClientsIdEditRoute: AdminClientsIdEditRoute,
}

const AdminClientsIdRouteWithChildren = AdminClientsIdRoute._addFileChildren(
  AdminClientsIdRouteChildren,
)

interface AdminClientsRouteRouteChildren {
  AdminClientsIdRoute: typeof AdminClientsIdRouteWithChildren
  AdminClientsCreateRoute: typeof AdminClientsCreateRoute
  AdminClientsIndexRoute: typeof AdminClientsIndexRoute
}

const AdminClientsRouteRouteChildren: AdminClientsRouteRouteChildren = {
  AdminClientsIdRoute: AdminClientsIdRouteWithChildren,
  AdminClientsCreateRoute: AdminClientsCreateRoute,
  AdminClientsIndexRoute: AdminClientsIndexRoute,
}

const AdminClientsRouteRouteWithChildren =
  AdminClientsRouteRoute._addFileChildren(AdminClientsRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminClientsRouteRoute: typeof AdminClientsRouteRouteWithChildren
  AdminEventsRoute: typeof AdminEventsRoute
  AdminPromosRoute: typeof AdminPromosRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminPartnersCreateRoute: typeof AdminPartnersCreateRoute
  AdminPartnersIndexRoute: typeof AdminPartnersIndexRoute
  AdminPartnersIdEditRoute: typeof AdminPartnersIdEditRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminClientsRouteRoute: AdminClientsRouteRouteWithChildren,
  AdminEventsRoute: AdminEventsRoute,
  AdminPromosRoute: AdminPromosRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminPartnersCreateRoute: AdminPartnersCreateRoute,
  AdminPartnersIndexRoute: AdminPartnersIndexRoute,
  AdminPartnersIdEditRoute: AdminPartnersIdEditRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface ClientesRouteRouteChildren {
  ClientesAvaliacoesRoute: typeof ClientesAvaliacoesRoute
  ClientesContatosRoute: typeof ClientesContatosRoute
  ClientesFavoritosRoute: typeof ClientesFavoritosRoute
  ClientesPainelClienteRoute: typeof ClientesPainelClienteRoute
  ClientesPerfilRoute: typeof ClientesPerfilRoute
  ClientesVouchersRoute: typeof ClientesVouchersRoute
  ClientesIndexRoute: typeof ClientesIndexRoute
}

const ClientesRouteRouteChildren: ClientesRouteRouteChildren = {
  ClientesAvaliacoesRoute: ClientesAvaliacoesRoute,
  ClientesContatosRoute: ClientesContatosRoute,
  ClientesFavoritosRoute: ClientesFavoritosRoute,
  ClientesPainelClienteRoute: ClientesPainelClienteRoute,
  ClientesPerfilRoute: ClientesPerfilRoute,
  ClientesVouchersRoute: ClientesVouchersRoute,
  ClientesIndexRoute: ClientesIndexRoute,
}

const ClientesRouteRouteWithChildren = ClientesRouteRoute._addFileChildren(
  ClientesRouteRouteChildren,
)

interface PainelRouteChildren {
  PainelAvaliacoesRoute: typeof PainelAvaliacoesRoute
  PainelConfiguracoesRoute: typeof PainelConfiguracoesRoute
  PainelEstatisticasRoute: typeof PainelEstatisticasRoute
  PainelImagensRoute: typeof PainelImagensRoute
  PainelPerfilRoute: typeof PainelPerfilRoute
  PainelPromocoesRoute: typeof PainelPromocoesRoute
  PainelReservasRoute: typeof PainelReservasRoute
  PainelIndexRoute: typeof PainelIndexRoute
}

const PainelRouteChildren: PainelRouteChildren = {
  PainelAvaliacoesRoute: PainelAvaliacoesRoute,
  PainelConfiguracoesRoute: PainelConfiguracoesRoute,
  PainelEstatisticasRoute: PainelEstatisticasRoute,
  PainelImagensRoute: PainelImagensRoute,
  PainelPerfilRoute: PainelPerfilRoute,
  PainelPromocoesRoute: PainelPromocoesRoute,
  PainelReservasRoute: PainelReservasRoute,
  PainelIndexRoute: PainelIndexRoute,
}

const PainelRouteWithChildren =
  PainelRoute._addFileChildren(PainelRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  ClientesRouteRoute: ClientesRouteRouteWithChildren,
  BuscarRoute: BuscarRoute,
  CadastroClienteRoute: CadastroClienteRoute,
  CategoriasRoute: CategoriasRoute,
  ClienteLoginRoute: ClienteLoginRoute,
  DefinirSenhaRoute: DefinirSenhaRoute,
  EntrarRoute: EntrarRoute,
  EntrarAdminRoute: EntrarAdminRoute,
  EventosRoute: EventosRoute,
  PainelRoute: PainelRouteWithChildren,
  PlanosRoute: PlanosRoute,
  PreservacaoRoute: PreservacaoRoute,
  CategoriaSlugRoute: CategoriaSlugRoute,
  ParceiroSlugRoute: ParceiroSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
